apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-demo-app
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: []
---


apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: dev cluster
gke:
 cluster: projects/gkemedium/locations/us-central1/clusters/autopilot-cluster-1
